# Generated by Django 5.2.6 on 2025-09-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='type',
            field=models.CharField(default='Engineeering', max_length=50),
        ),
        migrations.AlterField(
            model_name='college',
            name='college_type',
            field=models.CharField(default='Government', max_length=50),
        ),
    ]
