# Generated by Django 5.2.6 on 2025-09-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_college_type_alter_college_college_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='type',
        ),
    ]
